### ISSUE TITLE
Cannot get output interceptors handleMessage method to fire in Grails 3 version of plugin (latest)

### ISSUE THREAD

**Issue by rvanderwerf** [Grails-Plugin-Consortium/grails-cxf-client#61]
I am having an issue where I cannot get output interceptors to fire in the latest release for Grails 3. I am trying to inject authentication headers into the outgoing message. I have a Grails 3 app, which wires in the output interceptors like so in resources.groovy:
```
    wsAuthHeaderInjectorOutInterceptor(wsAuthHeaderInjectorOutInterceptor) {
        grailsApplication = ref('grailsApplication')
    }

    destWsLoginHeaderInjectorOutInterceptor(DestWsLoginHeaderInjectorOutInterceptor) {
        grailsApplication = ref('grailsApplication')
    }
```

My methods here, never fire even though I list in the application.yml definition for the service. I see on the classes the constructure is called successfully on application startup.
```
 public void handleMessage(SoapMessage message) {
     System.out.println("Here I am!!!")
 }
```
The method above never gets fired. It calls the remote endpoint and never runs it. Doesn't seem to matter which one.

I've configured it like so:
```
cxf:
  proxy:
    password: 'changeme'
    port: 3128
    server: 'aproxysomehwere'
    username: 'proxy-user'
  client:
    afancyWs:
      afancyUsername: 'username'
      afancyPassword: 'password'
      afancyWsVersion: '9.8'
      afancyCulture: com.afancyholidays.ws.Culture.EN_US
      clientInterface:  com.afancyholidays.ws.IFancyFlow
      serviceEndpointAddress: 'http://demows.afancyholidays.com/FancyFlow.svc/bas'
      inInterceptors: afancyLoggingInInterceptor, springGzipInInterceptor
#      outInterceptors: wsAuthHeaderInjectorOutInterceptor, afancyLoggingOutInterceptor, springGzipOutInterceptor, sAAJOutInterceptor
      outInterceptors: wsAuthHeaderInjectorOutInterceptor
      connectionTimeout: 120000
      receiveTimeout: 120000
      enableDefaultLoggingInterceptors: false
```
What I am sure of: stepped through the debugger and monitored netstat, my proxy settings are being used. I am sure the bean constructor is called when initialized. I've stepped through the CXF code and don't see my interceptors in the list it builds of them to call (PhaseInterceptorChain.java). I am sure the handleMessage method is not called, verified through stdout println, logger, and debugger. I've debugged through ClientImpl and PhaseIntercepterChain class where it gathers the interceptors to invoke but I just don't see mine in the list anywhere? It does know enough to call my interface, endpoint address, etc so it has to be reading my configuration for the basics anyways. This does work on the old grails 2.x version of the plugins.
